development:
  server: ‘http://fayeserver.herokuapp.com/faye ‘
  secret_token: “batkaro”
test:
  server: ‘http://fayeserver.herokuapp.com/faye ‘
  secret_token: “batkaro”
production:
  server: ‘http://fayeserver.herokuapp.com/faye ‘
  secret_token: “batkaro”
  signature_expiration: 86400 # one day